Project improvements
ShokoAnime/ShokoServer-WebUI pull request #253
Opened 2021-10-15 04:38 UTC by Codex-

Just a small set of project improvements based on what I saw at first glance when going to implement some features.

- @types are dev deps, not real deps, unless exported explicitly as a part of a package to be consumed.
- Updated the gitignore with things that were immediately generated and then git tracked.
- Abstracted the eslint rules out to a dedicated `.eslintrc.json`
  - Sorted / organised the file.
  - Added section to handle the JS config explicitly.
    - Means you can avoid the copy paste ignores.
  - Added `@typescript-eslint/await-thenable` & `@typescript-eslint/no-floating-promises`.
    - These two warn on what in my experience is one of the most common sources for bugs in applications.
- Improve the CICD workflows.
  - Bump to use latest `setup-node`.
  - Run lint / build and every commit.
  - Only generate artifacts for PR's (original behaviour).
- Update use of deprecated webpack config.

2021-10-15 04:39 UTC, Codex- commented
Rebased on webui v2 branch.

2021-10-15 04:51 UTC, Codex- commented on src/core/middlewares/signalr.ts
> +    await connectionLog?.stop();
If you want to float these promises then consider using an IIFE to make it explicitly clear that a floated promise is the intention, that is the intention behind how the eslint rule is configured.

2021-10-15 08:38 UTC, hidden4003 approved these changes

2021-10-16 07:59 UTC, hidden4003 requested changes

2021-10-16 07:59 UTC, hidden4003 commented on .github/workflows/CI.yml
> +        run: yarn install --immutable-cache # lock changes should already be committed.
docs say you are supposed to use --immutable as a replacement for --frozen-lockfile, not --immutable-cache

2021-10-16 07:59 UTC, hidden4003 commented on .github/workflows/Release.yml
> +        run: yarn install --frozen-lockfile --production=false
needs to be --immutable here as well

2021-10-16 10:19 UTC, Codex- commented on .github/workflows/CI.yml
> +        run: yarn install --immutable-cache # lock changes should already be committed.
`immutable` is default enabled in CI environments:
```
If the --immutable option is set (defaults to true on CI)
```

https://yarnpkg.com/cli/install
![image](https://user-images.githubusercontent.com/8297838/137583654-b079caf4-98e7-4d12-afcf-7dd6bd8b68ec.png)

`--immutable-cache` is more desirable behaviour for ensuring that CICD is running the intended and committed state of the repository.

2021-10-16 10:19 UTC, Codex- commented on .github/workflows/Release.yml
> +        run: yarn install --frozen-lockfile --production=false
Ah damn, will update this one. Probably shouldn't have the `production` modifier either

2021-10-17 00:27 UTC, Codex- commented on .github/workflows/CI.yml
> +        run: yarn install --immutable-cache # lock changes should already be committed.
Hmm odd, removed for now.

2021-10-17 06:20 UTC, merged