WIP: Information panels for Actions and Utilities
ShokoAnime/ShokoServer-WebUI pull request #409
Opened 2022-09-29 06:05 UTC by LexMalta

As a new user of Shoko I have no idea what all the different actions and utilities do - so I wanted to add a description of each of them into the UI.

@ElementalCrisis put together a design on discord which I'm intending to follow

This PR is a WIP, the content will come later, this is just the basics of the design thrown together to get some early feedback on visuals and code.

2022-09-29 06:11 UTC, harshithmohan commented
Not against writing it in scss but it would be better if there's a way to do the animations with just tailwind classes

2022-09-29 06:19 UTC, LexMalta commented
@harshithmohan I had a try at doing it that way, but I don't think it's possible to both define the keyframes and then use them for an animation all in one go?

2022-09-29 06:44 UTC, harshithmohan commented
We could go for a simpler animation maybe 🤔 
So, click and it just expands from the top, so a transition on height change perhaps. (that wouldn't need keyframes, I'm thinking)
That would match the style of other animations
@ElementalCrisis what do you think?

2022-09-29 06:44 UTC, harshithmohan commented
Also @LexMalta, you might want to check the linter errors

2022-09-29 07:11 UTC, ElementalCrisis commented
Make the tooltip width fixed as we don't want the sidepanel's total width to expand on click. As for the animation, I'd prefer a smoother one, maybe the same one we use for the headers themself?

2022-09-29 13:14 UTC, revam commented on src/components/Dialogs/ActionsModal.tsx
> +          <span className="inline-block text-highlight-1" onClick={() => item.runAction(item.name, item.function)}><Icon className="cursor-pointer" path={mdiPlayCircleOutline} size={1} /></span>
Why not just pass a `onClick` prop instead of the `function` and `runAction` props?

2022-09-29 13:14 UTC, revam commented on src/components/Dialogs/ActionsModal.tsx
> +        {items.map(item => <RenderItem {...quickActions[item]} runAction={runAction} />)}
If we can avoid it then please don't use the spread operator when rendering react elements. Also, if we don't spread then we don't need to pass the unused `data` property (until it's used at least) amd can omitn8t from the props object used by the `RenderItem` function.

2022-09-30 08:44 UTC, revam requested changes
Please fix the linter error. 😅

Otherwise it is looking good so far. 😃👍

2022-09-30 08:44 UTC, revam commented on src/components/Dialogs/ActionsModal.tsx
Linter error for unused import.

2022-09-30 08:44 UTC, revam commented on src/components/Dialogs/ActionsModal.tsx
> +const RenderItem = (item: { name:string, onClick:Function, info?:string }) => {
Much better 😃👍

2022-09-30 08:44 UTC, revam commented on src/core/quick-actions.ts
> +    info: 'Removes entries in Shoko and MyList for files thats are no longer accessible',
If you want then i can help adding the descriptions.

2022-09-30 08:49 UTC, revam commented
Also, some small advice; I will recommend running `yarn run lint` before pushing to catch any lint errors, because otherwise will the CI pipeline complain if you push and the changes contain any lint errors. 😅

2022-10-02 23:16 UTC, ElementalCrisis commented
Looking good @LexMalta, resolve the lint error and we can get this merged in.

2022-10-03 10:20 UTC, hidden4003 approved these changes

2022-10-03 10:26 UTC, merged